name: Feature Request
description: Suggest a new skill or enhancement
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please search [existing issues](https://github.com/LukasStrickler/ai-dev-atelier/issues) first to avoid duplicates.

  - type: checkboxes
    id: preflight
    attributes:
      label: Pre-flight Checklist
      options:
        - label: I have searched existing issues and this feature has not been requested.
          required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Describe it.
      placeholder: "I'm always frustrated when..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: A clear description of what you want to happen.
      placeholder: "I would like a skill that..."
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Category
      description: What type of feature is this?
      options:
        - "New skill"
        - "Enhancement to existing skill"
        - "MCP integration"
        - "Documentation"
        - "Developer experience"
        - "Other"
    validations:
      required: true

  - type: dropdown
    id: skill
    attributes:
      label: Related Skill (if applicable)
      description: Which skill does this relate to?
      options:
        - "N/A - New skill"
        - "code-quality"
        - "docs-check"
        - "docs-write"
        - "git-commit"
        - "code-review"
        - "resolve-pr-comments"
        - "search"
        - "research"
        - "ui-animation"
        - "use-graphite"

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any alternative solutions or workarounds you've thought about.

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other context, mockups, or examples that might help.
